### ISSUE TITLE
Use scale transformation instead of increasing the font-size

### ISSUE THREAD

**Issue by nc0fr** [nc0fr/website#17]
Using transformations allow for transitions, provide a better experience and can be timed.

**Comment by nc0fr** [comment]
From trail:
```css
p > a:hover {
  transform: scale(1.5);
  letter-spacing: 0.1em;
  transition: all .5s;
}
```
